### ISSUE TITLE
Supported operations query mechanism

### ISSUE THREAD

**Issue by ibelem** [webmachinelearning/webnn#504] opened 2024-01-12 02:02 UTC
We have seen ongoing WebNN implementation on Windows and ChromeOS, with WebNN prototype development underway for Android and macOS. In addition to computation on CPU and GPU devices, we have also seen leading hardware manufacturers increase their support for NPUs. 

Ideally, all APIs and operations defined by the WebNN specification would be fully supported on WebNN-enabled operating systems, devices. However, due to differences in software stacks and hardware, it is inevitable that some operations cannot be fully supported and require fallback via JavaScript machine learning frameworks or web applications. 

Given this, web developers want to know the current device and operating system, such as WebNN GPU on Windows or WebNN CPU on Android, and which operations are supported. It should be nice to have the query mechanism in the WebNN specification to allow JavaScript code to query which operations are supported by which operating system, device and and power preference after getting the MLContext object.

**Comment by ibelem** [comment] 2024-02-05 06:32
Based on https://issues.chromium.org/issues/41496343, detecting data types of WebNN is the other feature requirement besides the ops.

**Comment by inexorabletash** [comment] 2024-04-09 20:39
This seems to be a duplicate of #463 (including both ops and data types) so I'm going to close it, but if I missed any distinction please comment and we can re-open. Or add to the other issue.

**Closed by inexorabletash** 2024-04-09 20:39 UTC
Labels: feature request
