### ISSUE TITLE
Add traversal algorithm to buildSync()

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#448] opened 2023-08-14 10:22 UTC
_Originally posted by @huningxin in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1292713125_
              Looping |operand| in |outputs| only won't be able to validate and process the all operands and operators for the graph. Consider adding a graph traversal algorithm starting from |outputs|.

There is an implementation example: https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/renderer/modules/ml/webnn/ml_graph.cc;drc=ec360d3f928af69a303d413e806138b7624997e6;l=168?q=ml_graph.cc&ss=chromium

**Comment by inexorabletash** [comment] 2023-12-19 01:45
Does this include actually doing something with the names passed in as part of the record? They're validated, but so far as I can tell from the algorithm they're then dropped on the floor. I was looking at this as part of cleaning up for #450.

**Comment by reillyeon** [comment] 2023-12-19 02:32
> Does this include actually doing something with the names passed in as part of the record? They're validated, but so far as I can tell from the algorithm they're then dropped on the floor. I was looking at this as part of cleaning up for #450.

Looking at `buildSync(outputs)` more closely it looks like the problem is that what it means to register an operand as a graph output is not normatively defined and in particular does not add operand.[[descriptor]] to graph.[[outputDescriptors]] as is done for input operands. If it did then the operand name would be used.

**Comment by anssiko** [comment] 2024-02-01 14:20
When #531 is addressed, this issue can be closed.

**Comment by inexorabletash** [comment] 2024-02-01 20:06
The change in #531 just moves the algorithm from being in buildSync() and invoked in build() to being inline in build() - I think we still need a normative description of what build actually, either inline or in the Processing Model. So I disagree #531 addresses this.

**Comment by anssiko** [comment] 2024-02-15 10:57
With #531 addressed it looks like https://github.com/webmachinelearning/webnn/issues/448#issuecomment-1922144163 is the remaining work to be addressed prior to closing this issue.

**Closed** 2024-03-16 05:54 UTC
Labels: bug
