### ISSUE TITLE
Graph format

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [webmachinelearning/webnn#9] opened 2019-02-12 09:00 UTC
As I find it a separate topic to https://github.com/webmachinelearning/webnn/issues/3, would like to continue conversations about graph format itself (not operators and not api) here.

So far we have 3 major discussions:
1. If to include any graph format support
2. If it should be ONNX format
3. If it should be JSON format

For the reasons I gave in these (and other) posts:
 * https://github.com/webmachinelearning/webnn/issues/3#issuecomment-453056558
 * https://github.com/webmachinelearning/webnn/issues/3#issuecomment-458496943

I opt for option 3 - JSON format. 

Simple example with one hidden layer, 8 inputs and 9 outputs:

```javascript
{
  activation: "tanh",
  layers: [8, 14, 9]
}
```

Same NN as above, but with weights data provided:
```javascript
{
  activation: "tanh",
  layers: [8, 14, 9],
  setupData: 'ISEhIEhlbGxvIHdlYiBNTCAhISE='
}
```

Some "dummy" advanced example for JSON format:
```javascript
{
  domain: 'custom-domain',
  dataType: 'fp32',

  layers: [
    {
      name: "input",
      pipes: [
        {
          name: "A",
          size: 30,
          to: ['addIfAboveInputA'] 
        },
        {
          name: "B",
          size: 30
          to: ['addIfAboveInputB'] 
        }
      ]
    },
    {
      type: 'addIfAbove',
      a: 'addIfAboveInputA',
      b: 'addIfAboveInputB',
      value: 0
    },
    {
      type: 'onlyLowerThan',
      value: 50
    },
    {
      type: 'neurons',
      activation: 'tanh',
      size: 30
    },
    30
  ]

}
```

**Comment by anssiko** [comment] 2019-02-18 15:10
At chartering time, feedback was given it is important to define the following is [out of scope](https://webmachinelearning.github.io/charter/#out-of-scope):

>This Community Group does not attempt to mandate a specific neural network or Machine Learning model schema or format. Other groups are expected to address these requirements of this evolving area.


Given model formats are still evolving rapidly and there exists multiple such formats (and versions of each) that are in production use, defining a new model or graph format in this group is unlikely to contribute toward a solution ([mandatory xkcd](https://xkcd.com/927/)).

The current market accepted solution is to use model converters, also available as open source.

To conclude, the group chose option 1 initially. After revisiting related discussion in #3 I'm not seeing adequate support to change this at this time.

The issue is open to capture any further comments on the topic.

**Comment by anssiko** [comment] 2019-02-25 11:50
Hearing no further comments, I conclude the group is not interested in opening discussion on a new model or graph format at this time. This group position is consistent with the charter so no changes there.

**Closed by anssiko** 2019-02-25 11:50 UTC
